# This config file is used by ros2_control
spotarm/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tiago_gripper_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

spotarm/joint_trajectory_controller:
  ros__parameters:
    joints:
      - spotarm_1_joint
      - spotarm_2_joint
      - spotarm_3_joint
      - spotarm_4_joint
      - Slider11
      - spotarm_5_joint
      - spotarm_6_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

spotarm/tiago_gripper_joint_trajectory_controller:
  ros__parameters:
    joints:
      - gripper_left_finger_joint
      - gripper_right_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
